//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/paula/compiler/Calc.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CalcParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICalcListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] CalcParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] CalcParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CalcParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CalcParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.writeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteStatement([NotNull] CalcParser.WriteStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.writeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteStatement([NotNull] CalcParser.WriteStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] CalcParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] CalcParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableAssignment([NotNull] CalcParser.VariableAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableAssignment([NotNull] CalcParser.VariableAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] CalcParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] CalcParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadStatement([NotNull] CalcParser.ReadStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadStatement([NotNull] CalcParser.ReadStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CalcParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CalcParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] CalcParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] CalcParser.ExprContext context);
}
